### ISSUE TITLE
Unable to reproduce S-iPrompts on CDDB-hard

### ISSUE THREAD

**Issue by G-U-N** [iamwangyabin/S-Prompts#3]
Hi, thanks for your great work.

I have tried to reproduce the S-iPrompts on CDDB-hard, while the results is much lower than reported. 

Here is the final part of my training log:
```python
2022-11-26 22:52:52,356 [trainer.py] => CNN: {'total': 72.09, '00-01': 92.55, '02-03': 82.5, '04-05': 52.74, '06-07': 54.25, '08-09': 47.78, 'old': 72.51, 'new': 47.78}
2022-11-26 22:52:52,356 [trainer.py] => CNN top1 curve: [96.0, 91.29, 74.93, 73.15, 72.09]
```
Hence, 
`Task-wise AA`: mean([92.55, 82.5, 52.74, 54.25, 47.78]) = 65.96.
`Task-agnostic AA`: 72.09.

In the paper, it is reported that the `Task-wise AA` is 74.51. 

Could you provide the detailed training configs? I would really appreciate it.

**Comment by 4vicii** [comment]
hi, i changed **net_type** _slip_ to _sip_ in **cddb_sip.json**，but got a bug:

pretrained_cfg = resolve_pretrained_cfg(variant, kwargs=kwargs)
TypeError: resolve_pretrained_cfg() got an unexpected keyword argument 'kwargs'

how did you reproduce s-iprompts on cddb-hard?
